
services:
  prometheus:
    image: prom/prometheus:v2.14.0
    #    user: root
    ports:
      - '19090:9090'
    volumes:
      #      - /apps/prometheus/configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - /home/pathiknandi/projectdata/docker/data/prometheus/prometheus.yml:/etc/prometheus/config.yml
    command: '--config.file=/etc/prometheus/config.yml'

  grafana:
    image: grafana/grafana-oss:8.5.2
    ports:
      - '3000:3000'
    volumes:
      #      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - /home/pathiknandi/projectdata/docker/data/grafana:/var/lib/grafana
    #    user: "472"
    user: '104'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD-admin
      - GF_SERVER_DOMAIN=localhost